import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/navBar";

export const metadata: Metadata = {
  title: "ebouabbadi",
  description: "Generated by create next app",
  
};

export default function RootLayout({
  children,
  darkMode,
  toggleDarkMode,
}: Readonly<{
  children: React.ReactNode;
  darkMode: boolean;
  toggleDarkMode: () => void;
}>) {
  
  return (
    <html lang="en">
      <body className={`${darkMode ? 'dark' : ''} max-w-[2000px]`}>
       <NavBar toggleDarkMode={toggleDarkMode}/>
        {children}
        </body>
    </html>
  );
}
