import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/navBar";
import { useState } from "react";

export const metadata: Metadata = {
  title: "ebouabbadi",
  description: "Generated by create next app",
  
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  // const [dark, setDark] = useState(false); 

  return (
    <html lang="en">
      <body className=" darkh:bg-blue-4h00">
       <NavBar/>
        {children}
        </body>
    </html>
  );
}
