import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/navBar";

export const metadata: Metadata = {
  title: "ebouabbadi",
  description: "Generated by create next app",
  
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <body className={` max-w-[2000px]`}>
       <NavBar/>
        {children}
        </body>
    </html>
  );
}
